source "https://rubygems.org"
gemspec
gem "jemoji"
gem "faraday-retry"
gem "jekyll-search"
gem "jekyll-archives"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jekyll-include-cache"
gem "jekyll-seo-tag"
gem "csv"